# Generated by Django 4.0.1 on 2022-02-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desc',
            new_name='Y_pythoid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer',
        ),
    ]
