# Generated by Django 4.0.1 on 2022-02-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_rename_desc_item_y_pythoid_remove_item_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Y_pythoid',
            new_name='Y_id',
        ),
    ]
