# Generated by Django 4.0.1 on 2022-03-02 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_rename_y_pythoid_item_y_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Y_id',
            new_name='Youtube_id',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
